if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(KIT_PLATFORM_LINUX TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(KIT_PLATFORM_DARWIN TRUE)
elseif(WIN32)
    set(KIT_PLATFORM_WINDOWS TRUE)
else()
    message(FATAL_ERROR "Unsupported platform: ${CMAKE_SYSTEM_NAME}")
endif()

if(NOT MSVC)
    add_compile_options(-Wall -Wextra -Wpedantic -Werror)
    set(CMAKE_C_VISIBILITY_PRESET hidden)
    set(CMAKE_CXX_VISIBILITY_PRESET hidden)
    set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
else()
    add_compile_options(/W4 /WX)
endif()
